dist: xenial

language: node_js

node_js:
  - "node"
  - "lts/*"

before_script:
  - wget https://cs.symfony.com/download/php-cs-fixer-v2.phar

script:
  - cd /home/travis/build/nioc/own-my-money/money-front-vue && npm run lint
  - cd /home/travis/build/nioc/own-my-money/money-front-vue && npm run build
  - cd /home/travis/build/nioc/own-my-money/server && php /home/travis/build/nioc/own-my-money/php-cs-fixer-v2.phar fix -v --dry-run .
